name: CI_kendra

on: [pull_request, push]

jobs:
  run_kendra:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Run kendra tests
      run: |
        PYTHONPATH=$PWD python3 chc/cmdline/kendra/chc_test_kendrasets.py | tee kendra_output.txt
        diff kendra_output.txt tests/kendra/example_output/test_kendrasets.txt
